'use client';

import { useEffect, useMemo } from 'react';
import Link from 'next/link';
import { Plus, X } from 'lucide-react';
import { aircraft } from '@/lib/aircraft-data';
import { useMuseumStore } from '@/lib/store';

const fields = [['Role', 'role'], ['Introduced', 'introductionYear'], ['Status', 'status'], ['Max speed', 'maxSpeed'], ['Range', 'range'], ['Crew', 'crew'], ['Powerplant', 'engine'], ['Wingspan', 'wingspan']] as const;
export default function ComparePage() {
  const { compareList, addToCompare, removeFromCompare, clearCompare } = useMuseumStore();
  useEffect(() => { const add = new URLSearchParams(window.location.search).get('add'); if (add) addToCompare(add); }, [addToCompare]);
  const selected = useMemo(() => aircraft.filter((item) => compareList.includes(item.slug)), [compareList]);
  return <section className="mx-auto w-full max-w-7xl px-6 py-16"><p className="font-mono text-xs tracking-[.2em] text-accent">COMPARE MATRIX</p><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><h1 className="font-heading text-5xl">Place aircraft side by side</h1>{selected.length > 0 && <button onClick={clearCompare} className="text-sm text-muted-foreground hover:text-accent">Clear selection</button>}</div><p className="mt-4 max-w-2xl text-muted-foreground">Select up to four exhibits to compare their purpose, performance, and proportions.</p><div className="mt-9 flex flex-wrap gap-2">{aircraft.map((item) => { const selectedItem = compareList.includes(item.slug); return <button key={item.slug} onClick={() => selectedItem ? removeFromCompare(item.slug) : addToCompare(item.slug)} className={`rounded-full border px-3 py-2 text-sm transition ${selectedItem ? 'border-accent bg-accent/15 text-primary' : 'border-border text-muted-foreground hover:border-accent'}`}>{selectedItem ? <X className="mr-1 inline h-3 w-3" /> : <Plus className="mr-1 inline h-3 w-3" />}{item.name}</button>; })}</div>{selected.length ? <div className="mt-10 overflow-x-auto rounded-2xl border border-border"><table className="w-full min-w-[650px] border-collapse text-left"><thead className="bg-background-alt"><tr><th className="p-5 text-xs uppercase tracking-wider text-muted-foreground">Specification</th>{selected.map((item) => <th key={item.slug} className="p-5"><Link href={`/aircraft/${item.slug}`} className="font-heading text-xl hover:text-accent">{item.name}</Link><span className="mt-1 block text-xs font-normal text-muted-foreground">{item.manufacturer}</span></th>)}</tr></thead><tbody>{fields.map(([label, field]) => <tr key={label} className="border-t border-border"><th className="p-5 text-sm font-medium">{label}</th>{selected.map((item) => <td key={item.slug} className="p-5 text-sm text-muted-foreground">{item[field]}</td>)}</tr>)}</tbody></table></div> : <div className="mt-10 rounded-2xl border border-dashed border-border p-12 text-center"><h2 className="font-heading text-3xl">Your comparison table is empty.</h2><p className="mt-3 text-muted-foreground">Choose aircraft above, or start from the exhibit catalogue.</p><Link href="/aircraft" className="mt-6 inline-block text-sm font-medium text-accent">Browse exhibits →</Link></div>}</section>;
}
