import { notFound } from 'next/navigation';
import Link from 'next/link';
import { ArrowLeft, ChevronRight, Heart, Scale } from 'lucide-react';
import AircraftArt from '@/components/AircraftArt';
import { getAircraft } from '@/lib/aircraft-data';

export default async function AircraftPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const item = getAircraft(slug); if (!item) notFound();
  const specs = [['Max speed', item.maxSpeed], ['Range', item.range], ['Crew', item.crew], ['Powerplant', item.engine], ['Wingspan', item.wingspan], ['Length', item.length]];
  return <section className="mx-auto w-full max-w-7xl px-6 py-10"><Link href="/aircraft" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-accent"><ArrowLeft className="h-4 w-4" /> Back to exhibits</Link><div className="mt-6 grid gap-7 lg:grid-cols-[220px_minmax(0,1fr)_300px]"><aside className="order-2 lg:order-1"><p className="font-mono text-xs tracking-widest text-accent">CATEGORY</p><h2 className="mt-2 font-heading text-2xl">{item.category.replace(/-/g, ' ')}</h2><p className="mt-5 text-sm leading-6 text-muted-foreground">An archive entry examining the technical and cultural impact of this aircraft.</p><Link href={`/aircraft?category=${item.category}`} className="mt-5 inline-flex items-center gap-1 text-sm font-medium text-primary hover:text-accent">Explore collection <ChevronRight className="h-4 w-4" /></Link></aside><article className="order-1 lg:order-2"><AircraftArt item={item} className="h-[360px] rounded-2xl border border-slate-600 shadow-xl sm:h-[470px]" /><div className="mt-7"><p className="font-mono text-xs tracking-[.2em] text-accent">{item.introductionYear} · {item.manufacturer}</p><h1 className="mt-2 font-heading text-5xl">{item.name}</h1><p className="mt-4 text-lg leading-8 text-muted-foreground">{item.description}</p><div className="mt-6 flex gap-3"><Link href={`/compare?add=${item.slug}`} className="inline-flex items-center gap-2 rounded-full bg-primary px-4 py-2 text-sm text-primary-foreground"><Scale className="h-4 w-4" /> Compare</Link><button className="inline-flex items-center gap-2 rounded-full border border-border px-4 py-2 text-sm"><Heart className="h-4 w-4" /> Save</button></div></div></article><aside className="order-3 rounded-2xl border border-border bg-card p-6"><p className="font-mono text-xs tracking-[.2em] text-accent">FIELD GUIDE</p><dl className="mt-5 divide-y divide-border">{specs.map(([term, value]) => <div key={term} className="py-3"><dt className="text-xs uppercase tracking-wide text-muted-foreground">{term}</dt><dd className="mt-1 font-medium">{value}</dd></div>)}</dl></aside></div></section>;
}
